sudo: required
dist: trusty

language: c

matrix:
  include:
    - os: osx
    # - os: linux
    #   env: CC=clang CXX=clang++ npm_config_clang=1
    #   compiler: clang

node_js:
  - 6

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - libgnome-keyring-dev
      - xz-utils
      - xorriso
      - xvfb

install:
  - nvm install 6
  - npm install electron-builder@v18.6.2
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: dist/*.dmg
  skip_cleanup: true
  on:
    repo: https://github.com/yjlintw/comic-reader
    tags: true

branches:
  only: 
    - master
    - dev

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

notifications:
  slack: comicreader:$SLACK_TOKEN

script:
  - npm run dist